# This is a basic workflow to help you get started with Actions

name: Container Registry Transfer

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 */6 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  IMAGE_SYNCER_VERSION: v1.3.0
  ALIYUN_REGISTRY_USERNAME: ${{ secrets.ALIYUN_REGISTRY_USERNAME }}
  ALIYUN_REGISTRY_PASSWORD: ${{ secrets.ALIYUN_REGISTRY_PASSWORD }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  transfer:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Cache image syncer records
        uses: actions/cache@v2
        with:
          key: image-syncer
          path: |
            ~/.image-syncer/records

      # 安装 镜像同步工具
      - name: install image-sync tool
        run: |
          curl -LO "https://github.com/AliyunContainerService/image-syncer/releases/download/${IMAGE_SYNCER_VERSION}/image-syncer-${IMAGE_SYNCER_VERSION}-linux-amd64.tar.gz"
          tar -zxf image-syncer-${IMAGE_SYNCER_VERSION}-linux-amd64.tar.gz

      # 初始化 认证配置文件
      - name: init config.yaml with env
        run: |
          sed -i "s#ALIYUN_REGISTRY_USERNAME#${ALIYUN_REGISTRY_USERNAME}#g" auth.yaml
          sed -i "s#ALIYUN_REGISTRY_PASSWORD#${ALIYUN_REGISTRY_PASSWORD}#g" auth.yaml

      # 开始同步镜像
      - name: sync images
        run: ./image-syncer --proc=20 --auth=./auth.yaml --images=./images.yaml --records=~/.image-syncer/records --retries=3
